[package]
name = "pooly"
version = "0.1.0"
edition = "2021"
authors = ["P. Gli <pgli@pm.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.15"
actix-protobuf = "0.7.0-beta.3"
bytes = "1.1.0"
dashmap = "4.0.2"
deadpool = "0.9.2"
deadpool-postgres = "0.10.1"
postgres-types = "0.2.2"
prost = "0.8.0"
tokio-postgres = "0.7.5"
tokio-postgres-rustls = "0.9.0"
rustls = "0.20.2"

[build-dependencies]
prost-build = "0.8.0"