# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payloads.proto',
  package='payloads.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0epayloads.proto\x12\x0epayloads.proto\"J\n\x0cValueWrapper\x12\x10\n\x06string\x18\x01 \x01(\tH\x00\x12\x0e\n\x04int8\x18\x02 \x01(\x03H\x00\x12\x0f\n\x05\x62ytes\x18\x03 \x01(\x0cH\x00\x42\x07\n\x05value\"\x8d\x01\n\x0bJsonWrapper\x12\x33\n\x04\x62ody\x18\x01 \x03(\x0b\x32%.payloads.proto.JsonWrapper.BodyEntry\x1aI\n\tBodyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.payloads.proto.ValueWrapper:\x02\x38\x01\";\n\x0bRowResponse\x12,\n\x06values\x18\x01 \x03(\x0b\x32\x1c.payloads.proto.ValueWrapper\"P\n\rQueryResponse\x12\x14\n\x0c\x63olumn_names\x18\x01 \x03(\t\x12)\n\x04rows\x18\x02 \x03(\x0b\x32\x1b.payloads.proto.RowResponse\"Z\n\x0cQueryRequest\x12\r\n\x05\x64\x62_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12,\n\x06params\x18\x03 \x03(\x0b\x32\x1c.payloads.proto.ValueWrapperb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VALUEWRAPPER = _descriptor.Descriptor(
  name='ValueWrapper',
  full_name='payloads.proto.ValueWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='payloads.proto.ValueWrapper.string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int8', full_name='payloads.proto.ValueWrapper.int8', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='payloads.proto.ValueWrapper.bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='payloads.proto.ValueWrapper.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=34,
  serialized_end=108,
)


_JSONWRAPPER_BODYENTRY = _descriptor.Descriptor(
  name='BodyEntry',
  full_name='payloads.proto.JsonWrapper.BodyEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='payloads.proto.JsonWrapper.BodyEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='payloads.proto.JsonWrapper.BodyEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=252,
)

_JSONWRAPPER = _descriptor.Descriptor(
  name='JsonWrapper',
  full_name='payloads.proto.JsonWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='payloads.proto.JsonWrapper.body', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_JSONWRAPPER_BODYENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=252,
)


_ROWRESPONSE = _descriptor.Descriptor(
  name='RowResponse',
  full_name='payloads.proto.RowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='payloads.proto.RowResponse.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=313,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='payloads.proto.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_names', full_name='payloads.proto.QueryResponse.column_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='payloads.proto.QueryResponse.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=395,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='payloads.proto.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_id', full_name='payloads.proto.QueryRequest.db_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query', full_name='payloads.proto.QueryRequest.query', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='payloads.proto.QueryRequest.params', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=487,
)

_VALUEWRAPPER.oneofs_by_name['value'].fields.append(
  _VALUEWRAPPER.fields_by_name['string'])
_VALUEWRAPPER.fields_by_name['string'].containing_oneof = _VALUEWRAPPER.oneofs_by_name['value']
_VALUEWRAPPER.oneofs_by_name['value'].fields.append(
  _VALUEWRAPPER.fields_by_name['int8'])
_VALUEWRAPPER.fields_by_name['int8'].containing_oneof = _VALUEWRAPPER.oneofs_by_name['value']
_VALUEWRAPPER.oneofs_by_name['value'].fields.append(
  _VALUEWRAPPER.fields_by_name['bytes'])
_VALUEWRAPPER.fields_by_name['bytes'].containing_oneof = _VALUEWRAPPER.oneofs_by_name['value']
_JSONWRAPPER_BODYENTRY.fields_by_name['value'].message_type = _VALUEWRAPPER
_JSONWRAPPER_BODYENTRY.containing_type = _JSONWRAPPER
_JSONWRAPPER.fields_by_name['body'].message_type = _JSONWRAPPER_BODYENTRY
_ROWRESPONSE.fields_by_name['values'].message_type = _VALUEWRAPPER
_QUERYRESPONSE.fields_by_name['rows'].message_type = _ROWRESPONSE
_QUERYREQUEST.fields_by_name['params'].message_type = _VALUEWRAPPER
DESCRIPTOR.message_types_by_name['ValueWrapper'] = _VALUEWRAPPER
DESCRIPTOR.message_types_by_name['JsonWrapper'] = _JSONWRAPPER
DESCRIPTOR.message_types_by_name['RowResponse'] = _ROWRESPONSE
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST

ValueWrapper = _reflection.GeneratedProtocolMessageType('ValueWrapper', (_message.Message,), dict(
  DESCRIPTOR = _VALUEWRAPPER,
  __module__ = 'payloads_pb2'
  # @@protoc_insertion_point(class_scope:payloads.proto.ValueWrapper)
  ))
_sym_db.RegisterMessage(ValueWrapper)

JsonWrapper = _reflection.GeneratedProtocolMessageType('JsonWrapper', (_message.Message,), dict(

  BodyEntry = _reflection.GeneratedProtocolMessageType('BodyEntry', (_message.Message,), dict(
    DESCRIPTOR = _JSONWRAPPER_BODYENTRY,
    __module__ = 'payloads_pb2'
    # @@protoc_insertion_point(class_scope:payloads.proto.JsonWrapper.BodyEntry)
    ))
  ,
  DESCRIPTOR = _JSONWRAPPER,
  __module__ = 'payloads_pb2'
  # @@protoc_insertion_point(class_scope:payloads.proto.JsonWrapper)
  ))
_sym_db.RegisterMessage(JsonWrapper)
_sym_db.RegisterMessage(JsonWrapper.BodyEntry)

RowResponse = _reflection.GeneratedProtocolMessageType('RowResponse', (_message.Message,), dict(
  DESCRIPTOR = _ROWRESPONSE,
  __module__ = 'payloads_pb2'
  # @@protoc_insertion_point(class_scope:payloads.proto.RowResponse)
  ))
_sym_db.RegisterMessage(RowResponse)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'payloads_pb2'
  # @@protoc_insertion_point(class_scope:payloads.proto.QueryResponse)
  ))
_sym_db.RegisterMessage(QueryResponse)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'payloads_pb2'
  # @@protoc_insertion_point(class_scope:payloads.proto.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)


_JSONWRAPPER_BODYENTRY.has_options = True
_JSONWRAPPER_BODYENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
